const express = require('express')
const app = express()
const mongoose = require('mongoose')
const register = require('./hire/routes/signups')
const login = require('./hire/routes/login')
const cors = require('cors')
const available = require('./hire/routes/availables')
const posts = require('./hire/routes/postJobs')
const user = require('./seek/routes/users')
const category = require('./hire/routes/categories')
const logsin = require('./seek/routes/login')
const apply = require('./seek/routes/applyJobs')
app.use(express.json())
app.use(cors())
app.use('/hire/register', register)
app.use('/hire/login', login)
app.use('/hire/types', available)
app.use('/hire/posts', posts)
app.use('/hire/category', category)
app.use('/seek/register', user)
app.use('/seek/login', logsin)
app.use('/seek/apply', apply)

mongoose
    .connect('mongodb://localhost/kazi')
    .then(() => console.log('connected to mongo db'))
    .catch(() => console.log('failed to connect to mongo db'))

const port = process.env.PORT || 9000
app.listen(port, () => console.log(`listening on port ${port}`))